export { VelaError } from "./base";
export {
  AgentMandateAlreadyExistsError,
  AgentMandateNotFoundError,
  AmountExceedsPlanAmountError,
  DailyLimitExceededError,
  DuplicateServiceError,
  FrequencyTooLowError,
  InsufficientMandateBalanceError,
  InsufficientFundsError,
  InvalidAgentMandateStatusTransitionError,
  InvalidServiceListError,
  LifetimeCapExceededError,
  MandatePausedError,
  MandateRevokedError,
  MandateExpiredError,
  MandateNotActiveError,
  MaxPullsExceededError,
  MaxPullsTooLowError,
  NoFundsToDrainError,
  OverflowError,
  PlanNotActiveError,
  PullTooEarlyError,
  PullAmountTooSmallError,
  PullCooldownActiveError,
  UnauthorizedCancelError,
  UnauthorizedAgentError,
  UnauthorizedAgentMandateAuthorityError,
  UnauthorizedServiceError,
  UnauthorizedAdminError,
  ProtocolPausedError,
  ServiceDailyLimitExceededError,
  TooManyServicesError,
} from "./program-errors";
export {
  StreamInsufficientBalanceError,
  StreamMinIntervalError,
  StreamTerminalStatusError,
  WrongAccountTypeError,
} from "./stream-errors";
export { translateError } from "./translate";
